apiVersion: 1
groups:
    - orgId: 1
      name: Meshtastic
      folder: Meshtastic
      interval: 5m
      rules:
        - uid: fe9e2df3-d523-430b-bf69-15650aae2ed1
          title: Battery Charge Percent Low
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 86400
                to: 0
              datasourceUid: WIyb0ajVk
              model:
                datasource:
                    type: prometheus
                    uid: WIyb0ajVk
                disableTextWrap: false
                editorMode: code
                exemplar: false
                expr: meshtastic_Battery_level
                format: time_series
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                interval: ""
                intervalMs: 15000
                legendFormat: '{{node}}'
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: B
              relativeTimeRange:
                from: 86400
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                settings:
                    mode: ""
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 86400
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 30
                            - 15
                        type: within_range
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: Z8tUTtTSz
          panelId: 2
          noDataState: NoData
          execErrState: Error
          for: 0s
          annotations:
            __dashboardUid__: Z8tUTtTSz
            __panelId__: "2"
            description: Meshtastic Repeater {{index $labels "node"}} Battery is low {{ index $labels "A" }}
            summary: Meshtastic Repeater {{index $labels "node"}} Battery is low {{ index $labels "A" }}
          labels:
            A: A
          isPaused: false
        - uid: cef803ef-6cc1-49ac-8adc-6dd923a5749f
          title: Repeater extended absence
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: WIyb0ajVk
              model:
                disableTextWrap: false
                editorMode: builder
                expr: last_over_time(meshtastic_up[2h]) == 0
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: '{{node}}'
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1h
          labels:
            A: A
            rule_uid: c7f9d6b1-b6a1-4459-82ad-5fa78aceae3a
          isPaused: false
        - uid: c6d58206-4b32-4d17-846a-2a3d153f69ad
          title: Channel utilization
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 10800
                to: 0
              datasourceUid: WIyb0ajVk
              model:
                datasource:
                    type: prometheus
                    uid: WIyb0ajVk
                editorMode: code
                expr: meshtastic_Total_channel_utilization
                instant: false
                interval: ""
                intervalMs: 15000
                legendFormat: '{{node}}'
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              relativeTimeRange:
                from: 10800
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 10800
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 60
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: Z8tUTtTSz
          panelId: 6
          noDataState: NoData
          execErrState: Error
          for: 0s
          annotations:
            __dashboardUid__: Z8tUTtTSz
            __panelId__: "6"
            description: Channel utilization warning {{ index $labels "node" }}, {{ index $labels "A" }}
            summary: Channel utilization warning {{ index $labels "node" }}, {{ index $labels "A" }}
          labels: {}
          isPaused: false
        - uid: f0f46395-1d4c-4391-aabe-965f9e309607
          title: Battery Charge Percent Critical
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 10800
                to: 0
              datasourceUid: WIyb0ajVk
              model:
                datasource:
                    type: prometheus
                    uid: WIyb0ajVk
                disableTextWrap: false
                editorMode: builder
                expr: meshtastic_Battery_level
                fullMetaSearch: false
                includeNullMetadata: true
                instant: false
                interval: ""
                intervalMs: 15000
                legendFormat: '{{node}}'
                maxDataPoints: 43200
                range: true
                refId: A
                useBackend: false
            - refId: B
              relativeTimeRange:
                from: 10800
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 10800
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 15
                            - 0
                        type: lt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: Z8tUTtTSz
          panelId: 2
          noDataState: NoData
          execErrState: Error
          for: 0s
          annotations:
            __dashboardUid__: Z8tUTtTSz
            __panelId__: "2"
            description: Meeshtastic battery Level on {{ index $labels "node" }} CRITICAL {{ index $labels "A" }} !
            summary: Meshtastic battery Level on {{ index $labels "node" }} CRITICAL {{ index $labels "A" }}!
          labels:
            A: A
          isPaused: false
