{
 "title": "Meshtastic_Repeaters Telemetry",
 "tags": [ "Meshtastic" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Battery",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meshtastic_Battery_level{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Alerts count", "type": "alertlist", "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 } },
  {
   "title": "Channel Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meshtastic_Total_channel_utilization{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Locations",
   "type": "geomap",
   "description": "Requires alertmanager to mark alerting points red.",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "last_over_time(meshtastic_Latitude{instance=\"$node\",job=\"$job\"}[7d])",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "last_over_time(meshtastic_Longitude{instance=\"$node\",job=\"$job\"}[7d])",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "meshtastic_up{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "ALERTS{instance=\"$node\",job=\"$job\",alertstate=\"firing\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Alerts count", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 } },
  {
   "title": "Status over time",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum (meshtastic_up{instance=\"$node\",job=\"$job\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "meshtastic_Total_channel_utilization{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Battery Charge Percent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "meshtastic_Battery_level{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Transmit utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "meshtastic_Transmit_air_utilization{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "meshtastic_Voltage{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}